echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
echo "Plugin 'minibufexpl.vim'" >> ~/.vimrc
